services:
  api:
    image: cloudacademydevops/stocks-api:snowflake
    ports:
      - 9095:9095
    environment:
      - SNOWFLAKE_ACC=${SNOWFLAKE_ACC}
      - SNOWFLAKE_JAVA_PASSWORD=${SNOWFLAKE_JAVA_PASSWORD}
      - SNOWFLAKE_JAVA_URL=${SNOWFLAKE_JAVA_URL}
      - SNOWFLAKE_JAVA_USERNAME=${SNOWFLAKE_JAVA_USERNAME}
      - SNOWFLAKE_ROLE=${SNOWFLAKE_ROLE}
      - SNOWFLAKE_WH=${SNOWFLAKE_WH}
    networks:
      stocks:

  frontend:
    image: cloudacademydevops/stocks-app:latest
    ports:
      - 8000:8080
    links:
      - api
    environment:
      - REACT_APP_APIHOSTPORT=localhost:9095
    depends_on:
      - api
    networks:
      stocks:

networks:
  stocks:
    driver: bridge
