services:
  db:
    image: cloudacademydevops/stocks-db:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=fo11owth3wh1t3r4bb1t
    healthcheck:
      test: mysql -h127.0.0.1 -uroot -pfo11owth3wh1t3r4bb1t stocks
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      stocks:

  api:
    image: cloudacademydevops/stocks-api:latest
    ports:
      - 8080:8080
    links:
      - db
    environment:
      - DB_CONNSTR=jdbc:mysql://db:3306/stocks
      - DB_USER=root
      - DB_PASSWORD=fo11owth3wh1t3r4bb1t
    depends_on:
      db:
        condition: service_healthy
    networks:
      stocks:

  frontend:
    image: cloudacademydevops/stocks-app:latest
    ports:
      - 8000:8080
    links:
      - api
    environment:
      - REACT_APP_APIHOSTPORT=localhost:8080
    depends_on:
      - api
    networks:
      stocks:

networks:
  stocks:
    driver: bridge